# Generated by Django 5.1.3 on 2024-12-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
